# Generated by Django 4.2.5 on 2023-12-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t7',
            name='option1',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t7',
            name='option2',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t7',
            name='option3',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t7',
            name='option4',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
