# Generated by Django 4.2.5 on 2024-01-04 21:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_t7_option1_t7_option2_t7_option3_t7_option4'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=255, null=True)),
                ('sound_1', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('sound_2', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('sound_3', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('text_answer', models.CharField(default='', max_length=255, null=True)),
                ('student_best_sound', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('student_recent_sound', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.lesson')),
            ],
        ),
    ]
