# Generated by Django 4.2.5 on 2023-12-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_t7_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t7',
            name='answer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='T8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', null=True)),
                ('sound', models.ImageField(null=True, upload_to='test/')),
                ('answer', models.CharField(default='', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.lesson')),
            ],
        ),
    ]
