# Generated by Django 4.2.5 on 2024-02-12 21:15

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_speechquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t8',
            name='sound',
        ),
        migrations.AddField(
            model_name='t8',
            name='image',
            field=models.ImageField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
