# Generated by Django 4.2.5 on 2023-12-05 22:40

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_t7_answer_t8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t8',
            name='sound',
            field=models.ImageField(null=True, upload_to=project.models.path_define),
        ),
    ]
