# Generated by Django 4.2.5 on 2024-02-14 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_t8_sound_t8_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='t7',
            name='blanks_count',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Minimum value should be 1.')]),
        ),
    ]
