# Generated by Django 4.2.5 on 2024-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_t7_blanks_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t7',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
