# Generated by Django 4.2.5 on 2023-12-05 23:16

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_t8_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t8',
            name='sound',
            field=models.FileField(null=True, upload_to=project.models.path_define),
        ),
    ]
