# Generated by Django 4.2.5 on 2024-02-15 01:57

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_t7_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t5',
            old_name='sound',
            new_name='sound1',
        ),
        migrations.AddField(
            model_name='t5',
            name='image5',
            field=models.ImageField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='t5',
            name='image6',
            field=models.ImageField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='t5',
            name='number_of_life',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Minimum value should be 1.')]),
        ),
        migrations.AddField(
            model_name='t5',
            name='sound2',
            field=models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='t5',
            name='sound3',
            field=models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='t5',
            name='sound4',
            field=models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='t5',
            name='sound5',
            field=models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='t5',
            name='sound6',
            field=models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='t5',
            name='total_images',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Minimum value should be 1.')]),
        ),
        migrations.AlterField(
            model_name='t5',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
