# Generated by Django 4.2.5 on 2024-02-20 21:53

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_total_images_t5_total_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t5',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='t5',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='t5',
            name='sound5',
            field=models.FileField(blank=True, null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='t5',
            name='sound6',
            field=models.FileField(blank=True, null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
