# Generated by Django 4.2.5 on 2023-12-06 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_t4'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', null=True)),
                ('audio1', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('audio2', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('audio3', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('audio4', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('opt_audio1', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('opt_audio2', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('opt_audio3', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('opt_audio4', models.FileField(null=True, upload_to=project.models.path_define, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('answer', models.CharField(default='', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.lesson')),
            ],
        ),
    ]
